### ISSUE TITLE
Focus on delete: Last open buffer

### ISSUE THREAD

**Issue by traverseda** [willothy/nvim-cokeline#109]
It would be nice to keep track of the last open buffer, and be able to return to it when a buffer is deleted. This feature is especially handy when using neovim's terminal emulator mode, as I have commands like `git commit` set to edit text in a new buffer.

**Comment by willothy** [comment]
How's that ^ @traverseda?

**Comment by traverseda** [comment]
Looks good to me, I'll have to give it a try soon
