### ISSUE TITLE
When switching directories and entering NvimTree, Cokeline tries to access a nil value

### ISSUE THREAD

**Issue by Equilibris** [willothy/nvim-cokeline#117]
When changing work trees resulting in a NvimTree instance, Cokeline crashes with the following message:
```
2 / 2: Running post switch callbacks                                                                                                                                                    
E5108: Error executing lua ...ck/packer/start/nvim-cokeline/lua/cokeline/rendering.lua:102: attempt to index local 'current_buffer' (a nil value)                                       
stack traceback:                                                                                                                                                                        
        ...ck/packer/start/nvim-cokeline/lua/cokeline/rendering.lua:102: in function 'prepare'                                                                                          
        ...ck/packer/start/nvim-cokeline/lua/cokeline/rendering.lua:183: in function <...ck/packer/start/nvim-cokeline/lua/cokeline/rendering.lua:182>
```
I wonder if an if-check will fix this, so I will fork and then test.

My config is [here](https://github.com/Equilibris/nixpkgs/blob/main/nvim/lua/plugins/cokeline.lua)

**Comment by Equilibris** [comment]
The bug has been found. I had the option `show_if_buffers_are_at_least` set to `0`. This leads to unexpected behaviour. I have a PR patching this by simply disabling rendering if there are `0` buffers shown.

**Comment by Equilibris** [comment]
Pr created  #118

**Comment by Equilibris** [comment]
This error occurred solely from my stupidity, so it may not be required, but in case other people happen upon the same thing.

**Comment by willothy** [comment]
Thanks! I agree that it would be nice to have in case others make the same mistake.
