### ISSUE TITLE
Maybe let repetition of letters when using buffer_picker?

### ISSUE THREAD

**Issue by lucassperez** [willothy/nvim-cokeline#124]
Hey, I love your plugin, it gives us so much freedom and customizability! Thanks so much for this. 🙏

I just opened a PR about multibyte characters on buffer picker, but I also have a question about this functionality.

If we open and close buffers, the letters for buffer picker don't repeat, which is very clearly working as intended by looking at the code and the comments in the code, but wouldn't it be more intuitive if they did repeat? :thinking: For instance, if I set `letters` to be my homerow `asdfghjkl`, I think it would make sense for the first buffer to always be a, the second always be s etc.

What do you think? Maybe this could be configurable, have an option to recycle letters or not? Or maybe it would just be too much work? :sweat_smile:

I thought that maybe getting the letter using `buffer.index` could do it, but I don't really know all the implications, I didn't really dove that deep in the code, but it seems you put a lot of effort into not allowing exactly that, so it may be more complicated.

**Comment by willothy** [comment]
I like the idea of having that option! I believe Buffer.index should work consistently to get the pick character. I didn't write the pick file code so I can't speak to the original intentions, but I'll look into implementing this soon.

**Comment by willothy** [comment]
All done! I realized that that's how it should be by default. The current code is very much geared towards people using the filename to pick the char, so when picking sequentially from the list it could act a bit strange. #132 uses an index tracking mechanism instead of modifying the string, so that the picked characters will always appear in the same order.

**Comment by lucassperez** [comment]
Hey, I just updated here, it works great! The only thing is what happens when we have more buffers than letters configured? I know this is probably never gonna happen, but before it would show a `?` and now apparently it just shows nothing. I mean, it is just a silly edge case that seems very unlinkely, and maybe showing nothing/empty string is actually better, but I just wanted to let you know about it haha

Thanks again! I feel very confortable using this now, and it was so fast as well for your responses. 👏

**Comment by willothy** [comment]
Of course! Glad it works well. Not sure why it's not showing anything for you, I just tested and it's still showing a `?` for me.

**Comment by lucassperez** [comment]
Well, now that is very weird. My code is literally just this (it tries to get the first letter or the pick_letter):

```lua
text = function(buffer)
  if is_picking_focus() or is_picking_close() then
    return buffer.pick_letter
  end
  return vim.fn.strcharpart(buffer.unique_prefix .. buffer.filename, 0, 1)
end,
```

Well, I'm on neovim 0.9.1 if it matters.

Anyways, I just put a simple check like this and all's well

```lua
if buffer.pick_letter == '' then
  return '?'
end
```

But I decided to make weird decisions on my config to test more edge cases and realized that when using filenames, if we have more buffers than letters configured, it starts showing weird things instead of the first letter of the filename. I'm really trying to find kinda bizarre edge cases though! Haha

Something like this:

```lua
require('cokeline').setup({
  pick = {
    use_filename = true,
    letters = 'a',
  },
-- ...
```

Now if I open two files with names, say, `apples.lua` and `oranges.lua` and start picker, it shows `a` on both (happens if first file is orange and second is apple as well). But if I open two files with names `bananas.lua` and `oranges.lua` and start the picker, it shows `a` on bananas and `?` on oranges. And if I open like 3 or more files sometimes the `a` gets repeated. Anyways, it looks really weird when I don't have enough letters and use filenames, which is not the case in real life, but it is weird nonetheless.

But since the `?` issue happens here but not with you, I don't know if I trust myself! 😅

Anyways, thanks a bunch. ^^

**Comment by willothy** [comment]
I'm actually gonna reopen this for now since there are a few issues, definitely would like to work out those edge cases before considering this complete.

**Comment by willothy** [comment]
Fixed
