### ISSUE TITLE
Feature request: support sidebar padding on the right

### ISSUE THREAD

**Issue by FollieHiyuki** [willothy/nvim-cokeline#133]
Right now, `nvim-cokeline` only supports sidebar elements on the left. This works fine for common setup with NvimTree / NeoTree.

Some people, myself included, put other special windows on the right hand side (e.g. LSP symbol tree, treesitter inspect tree, ...). It would be nice to have another sidebar component there (probably with the same config as the left one).

**Comment by willothy** [comment]
Definitely would be nice to have.
