### ISSUE TITLE
Add commands for actions

### ISSUE THREAD

**Issue by vollowx** [willothy/nvim-cokeline#141]
In order to make easier key bindings, please add commands for Cokeline actions.

e.g.

- `CokelineNext`
- `CokelinePrevious`
- `CokelineDelete`
- `CokelinePick`
- `CokelineFocus` `<buf_id>`

**Comment by willothy** [comment]
It should be trivial to create keybindings using Lua functions... I may consider adding commands but I'm not sure it's really necessary.

**Comment by vollowx** [comment]
Well the main reason is that I still have not found that how to close buffer by key (the default bdelete command will maximize nvim-tree, but the buffer.close() function won't, but it's inside the setup config so that I can't bind it to key.

**Comment by willothy** [comment]
You can bind `require("cokeline.utils").buf_delete(bufnr, wipe?)`, or alternatively `require("cokeline.mappings").pick("close")` to pick which buffer to close. If you want to use the `Buffer:delete()` method, you can use `require("cokeline.buffers").get_current():delete()` or `require("cokeline.buffers").get_buffer(bufnr):delete()`. 

Hope that helps! If that's not sufficient, I'll start working on commands.

Btw, I am working on the wiki, but there's a good bit I still have to get through before it's complete.

**Comment by vollowx** [comment]
Thanks! That's enough for me, though giving commands is more friendly to new people, or you can simply add them to the wikis.
