### ISSUE TITLE
Custom function for sorting

### ISSUE THREAD

**Issue by sashalikesplanes** [willothy/nvim-cokeline#144]
I am trying to use a buffer line to show the current files I have marked using harpoon.

I want the buffers to be in the same order as in harpoon, is it possible to provide cokeline with a custom sorting function? In the code for buffers I only see functions for the default sort orders.

**Comment by willothy** [comment]
Currently you can only use the builtin functions. I should change that though, I'll add the ability to specify a function in the config as well.

**Comment by sashalikesplanes** [comment]
That’s awesome! Thanks for such a quick fix!

You rock!

**Comment by willothy** [comment]
> That’s awesome! Thanks for such a quick fix! You rock!

Thanks! Just happened at a convenient time and was pretty quick to implement. Btw I liked your idea so I implemented a Harpoon sorter:

```lua
local harpoon = require("harpoon.mark")
local function marknum(bufnr)
  local stat = harpoon.status(bufnr)
  -- harpoon.mark.status() returns "M%d" where %d is the index
  return tonumber(string.match(stat, "%d+"))
end

---@type a Buffer
---@type b Buffer
-- Use this in `buffers.new_buffers_position`
local function sorter(a, b)
  -- switch the a and b._valid_index to place non-harpoon buffers on the left
  -- side of the tabline - this puts them on the right.
  local ma = marknum(a)
  local mb = marknum(b)
  if ma == nil or mb == nil then
    ma = a._valid_index
    mb = b._valid_index
  end
  return ma < mb
end
```
