### ISSUE TITLE
Add `sp` highlight

### ISSUE THREAD

**Issue by AlexvZyl** [willothy/nvim-cokeline#147]
In Neovim, you can use `sp` (like `fg` and `bg`) to set the underline/undercurl color.  Though, it seems like cokeline does not support this.

**Comment by AlexvZyl** [comment]
I want to use `sp` to achieve this look, as I did with barbar:
![image](https://github.com/willothy/nvim-cokeline/assets/81622310/61a8e93b-a975-44fa-82c6-9168f2d9b97c)

**Comment by willothy** [comment]
I'll get this working tomorrow! Definitely would be nice to have.

**Comment by AlexvZyl** [comment]
Awesome!
