### ISSUE TITLE
nf-midi-close icon has been removed

### ISSUE THREAD

**Issue by perrin4869** [willothy/nvim-cokeline#148]
I was just trying out `cokeline`, but the `close` icon was not rendering correctly (see screenshot).
I looked for  at the [nerd-fonts cheatsheet](https://www.nerdfonts.com/cheat-sheet) website, and it seems to have been removed.
![2023-07-23_23:28:51](https://github.com/willothy/nvim-cokeline/assets/5774716/801938ad-a1ff-4575-90ca-0670198a3398)

**Comment by willothy** [comment]
Thanks for letting me know! I'll update the default close icon.

**Comment by perrin4869** [comment]
oh thanks for the tip! I'll update it :)
