### ISSUE TITLE
Component style function is ignored by plugin

### ISSUE THREAD

**Issue by BugLight** [willothy/nvim-cokeline#154]
Hi!
I'm experimenting with cokeline appearance. I've tried this in components section of config:
```lua
            {
                text = function(buffer) return buffer.unique_prefix .. buffer.filename end,
                style = function(buffer)
                    local attrs = {}
                    print('style:')
                    if buffer.is_modified then table.insert(attrs, 'italic') end
                    if buffer.is_focused then table.insert(attrs, 'bold') end
                    print(table.concat(attrs, ','))

                    return table.concat(attrs, ',')
                end,
            },
```
And that had no effect. Even prints didn't work. Seems like the style function had never been called.

Or have I missed something important? I will really appreciate any help :)

**Comment by willothy** [comment]
The style function is no longer a part of configs - sorry there may be some outdated readme sections, I'll try to get those fixed ASAP. You can set individual properties on each component such as `bold`, etc. to `boolean` or `fun(cx): boolean`.

**Comment by BugLight** [comment]
Now I get it. Thanks for clarifying!

**Comment by willothy** [comment]
No problem :)
