### ISSUE TITLE
Discarding and saving a modified buffer does not work

### ISSUE THREAD

**Issue by mweisshaupt1988** [willothy/nvim-cokeline#159]
Hi, first of all, I like this tabline plugin. It has finally replaced my old airline configuration. Thank you for that.

But I have noticed a problem with closing a modified buffer both through the close icon as well as calling the api ```
lua
require('cokeline/mappings').by_step('close', '0')```

I looked into the issue and it turned out that the result of the choice in utils.lua  buf_delete(bufnr, focus, wipeout) is not correctly evaluated or maybe my configuration broke it.

Instead of returning 1,2 or 3 it returns the String selected. I was able to locally fix it by modifying the code like this:
```lua
function(choice) 
      if choice == 1 or choice == "Save and close" then
        vim.api.nvim_buf_call(bufnr, vim.cmd.write)
        buf_del_impl(bufnr, focus_next, wipeout, false)
      elseif choice == 2 or choice == "Discard changes and close" then
        buf_del_impl(bufnr, focus_next, wipeout, true)
      elseif choice == 3 or choice == "Cancel" then
        return
      end
```
But I don't know if that is a good solution.

I'm using both telescope.nvim as well as dressing.nvim on Neovim 9.2 if that helps.

Also an additional thing is that in the case of "Save and close", this only works if the buffer has already a filename. It would be nice if the filename could be specified if empty.

**Comment by willothy** [comment]
Thanks for reporting! I'll get a fix in for this soon.

**Comment by willothy** [comment]
Also, just a note that you should use `.` in requires instead of `/`, it's not very well documented but there is a difference, `/` behaves more similarly to `dofile` than `require`.

**Comment by willothy** [comment]
Should be fixed in 2f80eebe

**Comment by mweisshaupt1988** [comment]
Thank you, it works perfectly. Also thanks for the hint, I didn't know there was a difference between `.` and `/` in the require statement.

**Comment by willothy** [comment]
Yeah, not sure if it's Neovim-specific or lua specific, but changing all of the requires in cokeline to use `.` did make a difference when I did that refactor a few months ago.
