### ISSUE TITLE
Bug: Error in `hlexists`

### ISSUE THREAD

**Issue by AlexvZyl** [willothy/nvim-cokeline#168]
Started getting this error recently, not sure what is wrong.  Happens even when I only do
```
require 'cokeline' .setup {}
```
for the config.

![image](https://github.com/willothy/nvim-cokeline/assets/81622310/129a75fe-8ce4-4b9d-adf5-237f5ceaa9af)

**Comment by willothy** [comment]
Thanks for reporting, I'll look into this today.

**Comment by willothy** [comment]
I'm not able to reproduce this, and in the defaults there should never be a dict passed to `hlexists`. What version of nvim are you using?

**Comment by AlexvZyl** [comment]
This error has noting to do with cokeline.  Apologies for the noise!
