### ISSUE TITLE
is_hovered events not working

### ISSUE THREAD

**Issue by sjclayton** [willothy/nvim-cokeline#176]
Is there anything special I have to configure in Neovim (options wise? I have mouse support enabled) to allow the buffer.is_hovered events to work?

I have tried my config under both nightly and the current stable version of Neovim, and hover events don't seem to happen in either.

EDIT: Nevermind, I figured it out.... I didn't have the mousemoveevent option set... Maybe this should be put into the documentation. 

Keep up the awesome work!!

**Comment by willothy** [comment]
Thanks! I'm actually going to reopen this as a reminder to myself, I definitely should add this to the docs.
