### ISSUE TITLE
Outdated Reference in README

### ISSUE THREAD

**Issue by mcDevnagh** [willothy/nvim-cokeline#180]
The README references `lua/cokeline/defaults.lua` [here](https://github.com/willothy/nvim-cokeline/blob/2e71292a37535fdbcf0f9500aeb141021d90af8b/README.md?plain=1#L654). However, the default config now lives [here](https://github.com/willothy/nvim-cokeline/blob/2e71292a37535fdbcf0f9500aeb141021d90af8b/lua/cokeline/config.lua#L14) as per [this commit](https://github.com/willothy/nvim-cokeline/commit/3682c78e0b727c12fb84405b694c14cc1af4d64b)

**Comment by willothy** [comment]
Thanks for reporting! I'll fix this soon :)
