### ISSUE TITLE
How do you remove the "x"?

### ISSUE THREAD

**Issue by krzkrzkrz** [willothy/nvim-cokeline#181]
How do you remove the "x"?

Additionally, how do you remove the ability to mouse click on the a buffer?

**Comment by willothy** [comment]
Click events are handled per-component, and the x is just a component in the default config. In your config, just don't include the 'x' component. You can copy and modify the default config from `cokeline/config.lua` if you don't already have a custom setup.

**Comment by krzkrzkrz** [comment]
Thank you
