### ISSUE TITLE
components config in README leads to no tabs being shown

### ISSUE THREAD

**Issue by alexander-gabriel** [willothy/nvim-cokeline#188]
The given default `default_hl.components` config is not the actual default and leads to no tabs being shown.

This should be updated or commented out soon, as people copying the config without adapting it, will end up with a non-functioning cokeline.

**Comment by willothy** [comment]
Sorry, I am not sure what you mean by this. There should not be a `default_hl.components` in the config...

**Comment by willothy** [comment]
Closing due to lack of response as I can't tell what the issue is and the config item you are referencing doesn't exist as far as I can tell.
