### ISSUE TITLE
Refresh function?

### ISSUE THREAD

**Issue by LucioMacarine** [willothy/nvim-cokeline#192]
Hello, i am currently trying to make the bufferline components change their background colors based on the current editor mode.
A simple publicly-accessible refresh function would suit my needs very well.
And i think i might be a nice addition to the project.

And also thanks for the amazing project ❤️ it's a really cool bufferline

**Comment by willothy** [comment]
Have you tried using the builtin `vim.cmd.redrawtabline`? This should invoke cokeline's tabline function and recompute each component's contents.

I am also reworking components to support async / event-driven updates - I don't have a timeframe for when the update will be released but this kind of thing should become much easier to implement (and more performant) when that is in.

**Comment by LucioMacarine** [comment]
It works just as expected, thanks!!
