### ISSUE TITLE
Drag Reordering only when mouse hovering tab

### ISSUE THREAD

**Issue by Meridolian** [willothy/nvim-cokeline#193]
Hi !
I enabled mouse (disable_mouse = false) so I can drag buffers and reorder them, but this feature works on the ENTIRE buffer. I mean if i click + drag inside the buffer, it does activate the buffers reordering.
This is pretty annoying because when i want to select lines or words in the buffer, the selection "freeze" until I release my mouse button.

Is it a bug or a feature ?

If it is a feature to reorder inside the buffer, is it possible to deactivate it or maybe just enable it only when hovering a tab ?

**Comment by willothy** [comment]
Hmm that is not the intended behavior, and is not how it works for me. Mouse mappings should work like normal. Mind providing some more info about your environment / nvim version?

**Comment by Meridolian** [comment]
Thanks for your reactivity ! :)

Here a video to show you what's happening : 
[Kooha-2024-02-29-16-33-28.webm](https://github.com/willothy/nvim-cokeline/assets/43091213/ff711398-5036-40b6-afe9-037b546faee2)

About my environment, I'm on Arch Linux with Hyprland (so Wayland), with a Nvidia GPU, Neovim 0.9.5, Cokeline installed from main branch.

and here's my cokeline config : 
`return {
    "willothy/nvim-cokeline";
    dependencies = {
        "stevearc/resession.nvim";
    };
    config = function()
        local palette = require("../config/palette")

        vim.o.mousemoveevent = true;  -- Needed for hover events

        require("cokeline").setup({
            show_if_buffers_are_at_least = 0;
            buffers = {
                filter_valid = false;
                focus_on_delete = "next";
                new_buffers_position = "last";
                delete_on_right_click = false;
            };
            mappings = {
                cycle_prev_next = true;
                disable_mouse = false;
            };
            history = {
                enabled = true;
                size = 50;
            };
            rendering = {
                max_buffer_width = 50;
            };
            pick = {
                use_filename = true;
                letters = "asdfjkl;ghnmxcvbziowerutyqpASDFJKLGHNMXCVBZIOWERTYQP";
            };
            default_hl = {
                fg = function(buffer)
                    return buffer.is_focused and palette.white or palette.dark_light;
                end;
                bg = function(buffer)
                    return buffer.is_focused and palette.dark_light or palette.dark;
                end;
                bold = true;
            };
            fill_hl = "Normal";
            components = {
                {
                    text = "";
                    fg = function(buffer)
                        if buffer.is_focused or buffer.buf_hovered then
                            return palette.green;
                        end;
                        return palette.dark_light;
                    end;
                    bg = palette.dark;
                    truncation = {
                        priority = 1;
                        direction = "middle";
                    }
                };
                {
                    text = function(buffer)
                        return " " .. buffer.devicon.icon;
                    end;
                    fg = function(buffer)
                        if buffer.is_focused or buffer.buf_hovered then
                            return palette.dark;
                        end;
                        return palette.white;
                    end;
                    bg = function(buffer)
                        if buffer.is_focused or buffer.buf_hovered then
                            return palette.green;
                        end;
                        return palette.dark_light;
                    end;
                    truncation = {
                        priority = 1;
                        direction = "middle";
                    }
                };
                {
                    text = function(buffer)
                        return buffer.filename;
                    end;
                    fg = function(buffer)
                        if buffer.is_focused or buffer.buf_hovered then
                            return palette.dark;
                        end;
                        return palette.white;
                    end;
                    bg = function(buffer)
                        if buffer.is_focused or buffer.buf_hovered then
                            return palette.green;
                        end;
                        return palette.dark_light;
                    end;
                    truncation = {
                        priority = 2;
                        direction = "right";
                    }
                };
                {
                    text = function(buffer)
                        if buffer.is_modified then
                            return "  ";
                        end;
                        if buffer.is_readonly then
                            return "  ";
                        end;
                        if buffer.is_hovered then
                            return " 󰅙 ";
                        end;
                        return " 󰅖 ";
                    end;
                    on_click = function(_, _, _, _, buffer)
                        buffer:delete();
                    end;
                    fg = function(buffer)
                        if buffer.is_focused or buffer.buf_hovered then
                            return palette.dark;
                        end;
                        return palette.white;
                    end;
                    bg = function(buffer)
                        if buffer.is_focused or buffer.buf_hovered then
                            return palette.green;
                        end;
                        return palette.dark_light;
                    end;
                    truncation = {
                        priority = 1;
                        direction = "middle";
                    }
                };
                {
                    text = "";
                    fg = function(buffer)
                        if buffer.is_focused or buffer.buf_hovered then
                            return palette.green;
                        end;
                        return palette.dark_light;
                    end;
                    bg = palette.dark;
                    truncation = {
                        priority = 1;
                        direction = "middle";
                    }
                };
            };
            sidebar = {
                filetype = { "neo-tree"; };
                components = {
                    {
                        text = "NeoTree";
                        fg = palette.purple;
                        bg = palette.dark;
                        bold = true;
                    };
                };
            };
        });
    end;
}`

**Comment by willothy** [comment]
Hmm, alright. Not sure what's causing this since you're on 0.9 so `vim.on_key` should be available. I'll look into this as soon as I can!

**Comment by Meridolian** [comment]
I tested it and it is fixed ! Thanks :smile: (really cool LFA pic btw)

**Comment by willothy** [comment]
Awesome!

Haha thanks, pretty sure I just found it on google in like 2015 and never changed it :rofl:
