### ISSUE TITLE
[bug]: disable_mouse doesn't work

### ISSUE THREAD

**Issue by tienbuigia** [willothy/nvim-cokeline#196]
```lua
local options = {
  show_if_buffers_are_at_least = 2,
  components = {
    {
      text = function(buffer) return ' ' .. buffer.filename .. ' ' end,
    }
  },
  mappings = { disable_mouse = true },
}
```

This is my config and mouse still works when I click the buffers.

**Comment by willothy** [comment]
Click functionality is built into Neovim, so it can't be disabled. The `disable_mouse` setting only affects the drag and hover functionality that's implemented in Cokeline. If you don't want clickable components, you can implement an `on_click()` handler for each component that does nothing. These click handlers will override the default click callback.
