### ISSUE TITLE
wiki example of harpoon sorter not working with harpoon2

### ISSUE THREAD

**Issue by niamleeson** [willothy/nvim-cokeline#199]
There is no module named `mark` anymore.

Harpoon2 branch:
https://github.com/ThePrimeagen/harpoon/tree/harpoon2

**Comment by willothy** [comment]
Yeah, I rewrote this for my config and forgot to update.

I'll update the wiki tomorrow, thanks for letting me know!

**Comment by willothy** [comment]
Updated :)

**Comment by niamleeson** [comment]
Thank you for the quick update! Really appreciate it!
