### ISSUE TITLE
Native tab support ?

### ISSUE THREAD

**Issue by kiuKisas** [willothy/nvim-cokeline#35]
Does an indicator for native tab is supported ? Can't find option about it..

**Comment by bellini666** [comment]
It would be useful to have an option to only display it also, like https://github.com/mg979/vim-xtabline does.

**Comment by olimorris** [comment]
Just to add that this would be a great little feature to have

**Comment by Barbaross93** [comment]
I found this plugin that offers customizing tabs as well as buffers: https://github.com/rafcamlet/tabline-framework.nvim

It'd still be nice to have tab support in cokeline as it offers more features/niceties out of the box.

**Comment by yyy33** [comment]
cool

**Comment by willothy** [comment]
This is 100% a planned feature!
