### ISSUE TITLE
Add `buffer.close_button_command` to resolve Nvim Tree `bdelete` issues. 

### ISSUE THREAD

**Issue by typkrft** [willothy/nvim-cokeline#56]
I'd be ok with adding a `buffer.close_button_command` option that's set to `bdelete` by default but can be configured to `Bdelete` if the user wants to. Having `bufdelete.nvim` as a hard dependency for everyone is not acceptable.

_Originally posted by @noib3 in https://github.com/noib3/nvim-cokeline/issues/55#issuecomment-1086947224_

This is the best interim solution for Nvim-Tree issues. Open for PRs. 

Related #44

**Comment by duarm** [comment]
Same problem, nvim-tree now requires a custom function to properly handle closing a buffer and focusing on the appropriate window. We need to hook that custom function to the close button cokeline provides.

```lua
function delete_curr_buffer()
	local cbn = vim.api.nvim_get_current_buf()
	local buffers = vim.fn.getbufinfo({ buflisted = true })
	local size = 0
	local idx = 0
	for n, e in ipairs(buffers) do
		size = size + 1
		if e.bufnr == cbn then
			idx = n
		end
	end

	if idx == 0 then return end

	if idx == size then
		vim.cmd("bprevious")
	else
		vim.cmd("bnext")
	end
	vim.cmd("bdelete " .. cbn)
end
```

**Comment by willothy** [comment]
Does this still need resolving?

**Comment by willothy** [comment]
on_click event will be in soon, current work in #106
