### ISSUE TITLE
Feature: sidebar offset support multiples filetypes

### ISSUE THREAD

**Issue by aspeddro** [willothy/nvim-cokeline#58]
It would be great if this option accepts multiple filetypes.

```lua
sidebar = {
  { 
    filetype = 'NvimTree',
    components = {
      {
        text = ' ',
        fg = colors.fg,
        bg = colors.bg_alt,
        style = 'bold',
      },
    },
  },
  {
    filetype = 'DiffviewFiles',
    components = {
      {
        text = ' ',
        fg = colors.fg,
        bg = colors.bg_alt,
        style = 'bold',
      },
    },
  }
},
```

**Comment by willothy** [comment]
Have you looked into [https://github.com/sidebar-nvim/sidebar.nvim](sidebar.nvim)? Seems like that might be what you're looking for.

**Comment by aspeddro** [comment]
No, this is a feature to apply offset based on file type.

**Comment by willothy** [comment]
Gotcha, my bad! Misunderstood the title. Will definitely look into this :)

**Comment by willothy** [comment]
Just to further clarify before I look into implementing this, you mean additional horizontal space for multiple side-by-side windows to the left of the main bufferline, correct?

**Comment by willothy** [comment]
Added the ability for multiple filetypes to be used as a sidebar by using a string  (like before) or list of strings for the `filetype` config option. 

For now they will be the same components, but I may consider adding ft-specific sidebar components in the future.
