### ISSUE TITLE
Updating diagnostics without saving a file with clangd

### ISSUE THREAD

**Issue by mrdakj** [willothy/nvim-cokeline#67]
Hi, is it possible to update a diagnostics without saving a file? Clangd is constantly updating while writing a code, so it emits an error during typing something (like "int x") but when finished typing error is gone from clangd side, but it is still shown in the tab. When file gets saved, error is gone as expected. So, error(s) always appears in tab during coding with clangd until file got saved. 
![diagnostics](https://user-images.githubusercontent.com/19488876/169252284-734c07b0-139d-4946-82fb-93d1078810be.png)

**Comment by willothy** [comment]
Can't repro and this has been inactive for a while, so going to close. Feel free to reopen if this is still an issue.
