### ISSUE TITLE
Difference in cokeline buffer order and internal buffer order

### ISSUE THREAD

**Issue by joleeee** [willothy/nvim-cokeline#73]
## Alternative title: Difference between `:bnext` and `(cokeline-focus-next)`

Whats the motivation behind this?

I had to change my :bn/bp keybinds to (cokeline-focus-next) / (cokeline-focus-prev), and im just wondering why the cokeline order and the native vim buffer order is not/doens not stay the same

**Comment by willothy** [comment]
I can't speak for the motivation, but I believe the ordering is extensible so that people can configure it. I would like to use my current binds as well, so I'll likely add more options for reordering soon.

**Comment by willothy** [comment]
you can now use the "number" ordering to replicate the default Neovim behavior.
