### ISSUE TITLE
Toggle buffer-bar visibility to hide/ unhide it from the window.

### ISSUE THREAD

**Issue by ghost** [willothy/nvim-cokeline#79]
Ability  to use a keybinding to hide the entire buffer bar like so:

_**BEFORE**_
![BUFF-visible](https://user-images.githubusercontent.com/82650811/190914508-5c128b80-f719-44df-bdc8-7b95932a3581.png)

_**AFTER**_
![buffer-invi](https://user-images.githubusercontent.com/82650811/190914513-843c0ccc-4aa3-4231-ab95-843fe79cc326.png)

**Comment by willothy** [comment]
Create a keybinding for `:set showtabline=...`, that should work :)
