### ISSUE TITLE
get_hex doesn’t work outside of setup unless reload

### ISSUE THREAD

**Issue by ckt114** [willothy/nvim-cokeline#86]
The `get_hex` doesn’t get the correct color unless used directly inside of `setup`.

_Does not work_
Will work if nvim config is reloaded while running. 
```
local bg = get_hex(“Normal”, “bg”)
require(“cokeline”).setup({
  components = {
    { text = “|”, bg = bg }
    …
  }
```

_Does work_
```
require(“cokeline”).setup({
  components = {
    { text = “|”, bg =  get_hex(“Normal”, “bg”) }
    …
  }
```

The problem with the second approach is that it’s not DRY. I know I can use `default_hl` for bg but there are highlights that I want to use repeatedly without having to call get_hex with same parameters multiple times.

**Comment by willothy** [comment]
I remember this happening a while back and can't repro now, so I believe this has been fixed. Feel free to reopen if this is still happening.
