### ISSUE TITLE
Add support for BufferLineCloseLeft and BufferLineCloseRight?

### ISSUE THREAD

**Issue by tmpm697** [willothy/nvim-cokeline#90]
Thanks for this nice buffer line, it works exceptionally well with auto-session and neo-tree.  I find it pretty much use them to quick clean up messy buffer session instead of closing each one.

can you add support for this feature?

**Comment by willothy** [comment]
Do you mean closing the buffer to the left and right of the current buffer? I'll definitely look into implementing that, it would be quite useful.
