### ISSUE TITLE
Upload examples images to user-images.githubusercontent.com to reduce plugin size

### ISSUE THREAD

**Issue by bournedrewd** [willothy/nvim-cokeline#91]
A slightly petty issue, but due to the fact that all configuration images are saved within the .github directory, the size of this plugin is considerably large with ~10Mb because of all the image files compared to <1Mb for most other plugins.

The majority of other (neo)vim plugins are much more lightweight by storing all configuration images on  "user-images.githubusercontent.com/\<hash>/\<hash>" which is achieved by dragging and dropping the image while in the GitHub editor.
Utilizing this approach, the size of the plugin could be cut down a lot, however, this comes at the cost that all examples images are slightly harder to maintain. Still, since most other plugins do this as well, perhaps this could be a minor thing to consider?

Example of uploading an image to GitHub is here:
https://user-images.githubusercontent.com/12532091/135542114-0dc6044b-43d2-455e-b7fe-85b838b69a2b.gif

**Comment by willothy** [comment]
Done!
