### ISSUE TITLE
[BUG] Settings focus_on_delete and new_buffers_position cause buffers not deleted?

### ISSUE THREAD

**Issue by tmpm697** [willothy/nvim-cokeline#93]
I use this plugin with https://github.com/olimorris/persisted.nvim. Before switch session i will clear/delete all current buffers, but with these two `focus_on_delete`, `new_buffers_position` options set to whatever values, `%bd!` would not clear all current buffers.

There's still one buffer left and that'll cause this one buffer somehow `restore` into switching session. But it's not reliable that this left buffer will always introduce into switching session. more like randomly.

Step:
1. set one of above options or both
2. cd /path/to/A, and open some file, let persisted auto-save this session
3. same as 2 but under /path/to/B
4. cd /path/to/C, then open nvim and then quit immediately
5. cd ~
6. nvim
7. :Telescope persisted, switch back and forth from A <--> B, everything works
8. :qa
9. nvim
10. :Telescope persisted, switch to A or B, then switch to C, open a new file to edit --> the left buffer will appear here.

**Comment by willothy** [comment]
Not sure about this one, but #103 may have fixed it?
