### ISSUE TITLE
Not Showing Devicons in the tabline

### ISSUE THREAD

**Issue by sanchit1053** [willothy/nvim-cokeline#94]
![image](https://user-images.githubusercontent.com/81797966/212982481-08d7ab2b-de1b-4dc2-a26a-9939a8806ed1.png)

The Tab Is not showing the devicons even when I have the require statement in packer and using as is one of the configurations with devicons given, 
I have checked and the configuration does indeed have devicons added,

Can you please help me?

**Comment by willothy** [comment]
Mind sharing your config?

**Comment by sanchit1053** [comment]
Sorry, the problem was fixed, I had some confusion about packer requires and wants and the devicons were not being called correctly
