### ISSUE TITLE
is this project abandoned/dead?

### ISSUE THREAD

**Issue by airtonix** [willothy/nvim-cokeline#98]
Only recent ticket activity is ticket authors self closing.

**Comment by noib3** [comment]
I'll probably make a post on the Neovim subreddit asking if someone wants to maintain it. I'm focusing on other projects right now and don't have time/energy/motivation to maintain or continue developing this plugin.

If someone steps in I'd be happy to give ownership to someone else, which would also involve moving the repo to their account.

**Comment by willothy** [comment]
> If someone steps in I'd be happy to give ownership to them, which would also involve moving the repo to their account.

I'd be interested in maintaining and working on this if that's something you're open to! I'm currently using it and have some feature ideas (and free time). :)

**Comment by noib3** [comment]
> I'd be interested in maintaining and working on this if that's something you're open to!

Absolutely! Can you delete your fork? I tried initiating the transfer but I can't because "willothy/nvim-cokeline already exists".

**Comment by noib3** [comment]
Transfered it.

**Comment by willothy** [comment]
Thanks! I'll get to work, already spent a good amount of time looking over the codebase :)

**Comment by noib3** [comment]
Godspeed!

**Comment by airtonix** [comment]
Amazing! 
 
 Glad I could bring you two souls together. 🤝
